spatial_dims: 2
in_channels: 1
out_channels: 1
num_channels: !!python/tuple [128, 256, 256]
attention_levels: !!python/tuple [False, True, True]
num_res_blocks: 1
num_head_channels: 256

model_path: models/custom_image_weights_128.pt