conditioning:
  method: wiener
  params:
    scale: 0.3
    # scale: 0.3

data:
  name: ellipse
  root: ./data/ellipse_samples/

intensity: 0
kernel: gaussian
kernel_size: 64
# kernel_std: [[9, 0], [0, 9]]
kernel_std: 3.0


measurement:
  noise:
    name: gaussian
    sigma: 0.02
  operator:
    name: blind_blur
