conditioning:
  method: richardson-lucy
  params:
    scale: 1.0
    # scale: 0.3

data:
  name: ffhq
  root: /home/modrzyk/code/data/ffhq-dataset/images1024x1024/00000/

measurement:
  noise:
    name: gaussian
    sigma: 0.02
  operator:
    name: gaussian_blur
    kernel_size: 61
    intensity: 3.0
