conditioning:
  method: ps
  params:
    scale: 0.3
data:
  name: ffhq
  root: ./data/ellipse_samples/
intensity: 0
kernel: gaussian
kernel_size: 64
kernel_std: [[6, 1], [4, 8]]
measurement:
  noise:
    name: gaussian
    sigma: 0.02
  operator:
    name: blind_blur
