conditioning:
  method: mlem
  params:
    scale: 0.3
    # scale: 0.3

data:
  name: ellipse
  root: /home/modrzyk/code/data/ellipses/img/val/
  # root: /home/modrzyk/code/blind-dps/data/ellipse_samples/

intensity: 0
kernel_size: 65
kernel_std: 3.0
kernel: gaussian
# kernel_std: [[9, 0], [0, 9]]


measurement:
  noise:
    name: gaussian
    sigma: 0.05
  operator:
    name: gaussian_blur
    kernel_size: 61
    intensity: 3.0
