conditioning:
  method: richardson-lucy
  params:
    scale: 0.3
    # scale: 0.3

data:
  name: ellipse
  # root: /home/modrzyk/code/data/ellipses/img/val/
  root: /home/modrzyk/code/blind-dps/data/ellipse_samples/

measurement:
  noise:
    name: gaussian
    sigma: 0.05
  operator:
    name: gaussian_blur
    kernel_size: 61
    intensity: 3.0
