conditioning:
  method: richardson-lucy
  params:
    scale: 0.3
    # scale: 0.3

data:
  name: ffhq
  root: ./data/samples/

measurement:
  noise:
    name: gaussian
    sigma: 0.02
  operator:
    name: gaussian_blur
    kernel_size: 61
    intensity: 3.0
